# Generated by Django 5.2.1 on 2025-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
